name: chuyendecoso
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  http: ^0.13.4
  permission_handler: ^9.2.0
  file_picker: ^4.5.1
  open_file: ^3.2.1
  provider: ^6.0.3
  get_it: ^7.2.0
  path_provider: ^2.0.9
  shared_preferences: ^2.0.13
  image_picker: ^0.8.5+3
  cupertino_icons: ^1.0.2
  path_provider_android: ^2.0.16
  firebase_auth: ^3.6.2
  firebase_core: ^1.20.0
  firebase_storage: ^10.3.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
  assets:
    - assets/images/
  